title: 前端学习计划
description: 资深后端工程师 → 前端全栈：一个月超级详细学习计划
lang: zh-CN
baseurl: "/learn-frontend"
url: "https://clumsy456.github.io"
theme: minima
markdown: kramdown
kramdown:
  input: GFM

collections:
  lessons:
    output: true
    permalink: /lessons/:name/

header_pages:
  - index.md
  - _pages/overview.md

exclude:
  - README.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
